#Installing required dependencies

- hosts: all
  tasks:
    - name: "Copying JDK File to Target"
      copy:
        src: "/root/jdk-8u171-linux-x64.rpm"
        dest: "/root/"

    - name: "Copying Hadoop File"
      copy: 
        src: "/root/hadoop-1.2.1-1.x86_64.rpm"
        dest: "/root/"

    - name: "Installing JDK"
      command: "rpm -i jdk-8u171-linux-x64.rpm --force"

    - name: "Installing Hadoop Software"
      command: "rpm -i hadoop-1.2.1-1.x86_64.rpm --force"

#Configuring Name Node (Here, Contoller Node is being set up as Name Node)

- hosts: master
  vars_prompt:
    - name: "name_dir"
      prompt: "Enter the shared directory of Name Node "
      private: no
 
  tasks:
    - name: "Creating the required directory"
      file:
        state: directory
        path: "{{ name_dir }}"
    - name: "Updating hdfs-site.xml file in Name Node"
      template:
        src: "/root/master_hdfs.xml"
        dest: "/etc/hadoop/hdfs-site.xml"

#Configuring Data Node 

- hosts: slave
  vars_prompt:
    - name: "data_dir"
      prompt: "Enter the shared directory of Data Node"
      private: no

  tasks:
    - name: "Creating the required directory."
      file:
        state: directory
        path: "{{ data_dir }}"
    - name: "Updating hdfs-site.xml file in Data Node"
      template:
        src: "/root/client_hdfs.xml"
        dest: "/etc/hadoop/hdfs-site.xml"

#Updating Core file in Name Node and Data Node

- hosts: all
  vars_prompt: 
    - name: "hport"
      prompt: "Enter the port number of Hadoop Daemon "
      private: no
  tasks:
    - name: "Updating the core-site.xml file"
      template:
        src: "/root/core.xml"
        dest: "/etc/hadoop/core-site.xml"

#Formatting and Starting Name Node

- hosts: master
  tasks:
    - name: "Formatting Name Node. "
      command: "hadoop namenode -format -force"
    - name: "Starting the Name Node"
      command: "hadoop-daemon.sh start namenode"
    - name: "Switching the Safe Mode OFF"
      command: "hadoop dfsadmin -safemode leave"
     
  
#Starting Data Node

- hosts: slave
  tasks:
    - name: "Starting Data Node."
      command: "hadoop-daemon.sh start datanode"


        


